#!/bin/bash

user=$(jira me)

function get_user() {
    if test -n "$1"; then
        user=$1
    elif test ! -t 0; then
        user=$( cat )
    fi
}

get_user $1

jira sprint list --current -a"$user" -s"In Progress" --columns key --plain --no-headers | xargs
exit $?
