#!/bin/bash

source "$(dirname "$0")/../aux/get-param.sh"

get-param-func $1

if [[ "$?" -eq 1 ]]; then
    echo "Error: Provide child issue key."
    exit 1
fi

child=$ret

curl \
    -s \
    -X GET \
    -H "Content-Type: application/json" \
    -H "Accept: application/json" \
    -H "Authorization: Bearer $JIRA_API_TOKEN" \
    http://jira.tecgraf.puc-rio.br:8080/jira/rest/api/latest/issue/$child \
        | python2 -c "import sys, json; print json.load(sys.stdin)['fields']['parent']['key']"

exit $?
