#!/bin/bash

source "$(dirname "$0")/../aux/get-param.sh"

get-param-func $1

if [[ "$?" -eq 1 ]]; then
    echo "Error: Provide parent issue key."
    exit 1
fi

parent=$ret

jira issue list --parent $parent --columns parent,summary,status,assignee -s~"Closed"

exit $? 
