#!/bin/bash

key=`jira me | doing`
summary=`jira issue list -q "key = $key" --plain --no-headers --columns summary | sed "s/$key[ \t]*//g"`
msg="[`parent $key`][$key] $summary"

git commit -am "$msg"
exit $?
