#!/bin/bash

source "$(dirname "$0")/../aux/get-param.sh"

# git 1.8.4
if [ -d "/opt/rh/devtoolset-2/" ]; then
    export PATH="/opt/rh/devtoolset-2/root/usr/bin/":$PATH
fi

get-param-func $1

if [[ "$?" -eq 1 ]]; then
    echo "Error: Provide target branch."
    exit 1
fi

target_branch=$ret

label=`jira me | doing | team`

glab mr create \
    --fill \
    --fill-commit-body \
    --assignee `jira me` \
    --allow-collaboration \
    --remove-source-branch \
    --target-branch $target_branch \
    --label "$label" \
    --push \
    --yes

exit $?
