#!/bin/bash

source "$(dirname "$0")/../aux/get-param.sh"

get-param-func $1

if [[ "$?" -eq 1 ]]; then
    echo "Error: Provide parent key."
    exit 1
fi

parent=$ret

declare -a names=("Log" "Valgrind" "Teste" "Validação" "Revisar report description")
 
for name in "${names[@]}"; do
    jira issue create --parent "$parent" -t"Technical task" -s"$name" --no-input
done

exit $?
