#!/bin/bash

# git 1.8.4
if [ -d "/opt/rh/devtoolset-2/" ]; then
    export PATH="/opt/rh/devtoolset-2/root/usr/bin/":$PATH
fi

label=`doing | team`

glab mr create \
    --fill \
    --fill-commit-body \
    --assignee `jira me` \
    --allow-collaboration \
    --remove-source-branch \
    --target-branch master \
    --label "$label" \
    --push \
    --yes && \
    mv-issue `doing` "Ready To Code Review"

exit $?
