#!/bin/bash

source "$(dirname "$0")/../aux/get-param.sh"

get-param-func $1

if [[ "$?" -eq 1 ]]; then
    echo "Error: Provide string."
    exit 1
fi

string=$ret

echo $string | tr '[:lower:]' '[:upper:]'

exit $? 
